### ISSUE TITLE
Create basic sprites for Dat Boi & Dolan

### ISSUE THREAD

**Issue by BurningTurtle** [BurningTurtle/MemeAttack#3]

**Comment by THE-BYN** [comment]
Dolan V1
![dolan sprite v1](https://cloud.githubusercontent.com/assets/27024488/25441083/9048efa0-2aa1-11e7-96ab-099cde903c7a.png)

**Comment by BurningTurtle** [comment]
Dat Boi is finished.

**Comment by THE-BYN** [comment]
Done
