### ISSUE TITLE
Change Dolan's attack to 4 knifes.

### ISSUE THREAD

**Issue by BurningTurtle** [BurningTurtle/MemeAttack#30]
One shooting towards the player, the other 3 in 90° intervals.

**Comment by THE-BYN** [comment]
That wouldn't make any difference to just shooting one knife, because the other knives won't hit the player anyways. Rather let him shoot 4 knives either diagonally or in the directions of the dimensions.

**Comment by THE-BYN** [comment]
ay

**Comment by BurningTurtle** [comment]
Have to be improved.

**Comment by BurningTurtle** [comment]
Improved.
