### ISSUE TITLE
Dolan stops shooting after some time

### ISSUE THREAD

**Issue by BurningTurtle** [BurningTurtle/MemeAttack#33]
Or he shoots just two knifes.
Should be fixed easily, but I have no time right now.

**Comment by THE-BYN** [comment]
` // Update our vector
        Vector2 playerVector2 = new Vector2(player.transform.position.x - knife2.transform.position.x, player.transform.position.y - knife2.transform.position.y);
        Vector2 playerVector3 = new Vector2(player.transform.position.x - knife3.transform.position.x, player.transform.position.y - knife3.transform.position.y);
        Vector2 playerVector4 = new Vector2(player.transform.position.x - knife4.transform.position.x, player.transform.position.y - knife4.transform.position.y);`

In these lines you are trying to access the knives, even if they got destroyed by touching the player beforehand.

By the way, why does knife1 get destroyed earlier?
`// Wait and Destroy the knife
        yield return new WaitForSeconds(1f);
        Destroy(knife1.gameObject);`

I also don't have any time right now to fix it right now, but there is the bug.

**Comment by BurningTurtle** [comment]
> By the way, why does knife1 get destroyed earlier?
Because knife1 shoots onto the player anyway, so firing it back again would make no real sense.
Would be too hard as well

**Comment by BurningTurtle** [comment]
Donee
